### ISSUE TITLE
Add helpful functions/examples to Julia

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/thermobench#40]
Julia module is quite helpful for the processing Thermobench data. Still, some additional functions (or examples) would make the work easier. Namely:

- `read` function allows one to access raw data; however, some data are missing. Are there options to interpolate/remove the missing data? Also, after interpolating the data, function exporting the data back to .csv would be helpful. 
- sometimes, one is interested in some specific time-series, then pipeline like: load data -> pick time-series (-> interpolate or process, if needed) -> write back to some csv - might be automated.
- `multi_fit` function is useful when analyzing the T_inf and OPS of various benchmarks; for accessing the estimated steady state temperatures for further processing, I am currently using `CSV.write("table.csv", select(mf.result, Not([:fit,:data,:series])))`; function doing that automatically would be nice.
- `multi_fit` plus functions like `plot_Tinf_and_ops` make nice comparisons across various benchmarks, but seemingly only for T_inf and OPS; now we might be able to measure even the Power (and possibly other things) - would it be possible to load multiple results, and plot bar charts similar to `T_inf_and_ops` which would be showing, e.g., average of a selected column (e.g., power)?
- add `title` argument to plot function

Most of these functions might already exist, but for non-Julia-expert it is not straightforward to use them. Maybe just adding some additional examples into the documentation might help.

**Comment by wentasah** [comment]
> Julia module is quite helpful for the processing Thermobench data. Still, some additional functions (or examples) would make the work easier. Namely:
> 
>  * `read` function allows one to access raw data; however, some data are missing. Are there options to interpolate/remove the missing data? 

I added that to the documentation. See 41c4b6e76e2fe6b707821a18a6fdd04bac6deb1b and https://ctu-iig.github.io/thermobench/dev/#Missing-values-and-interpolation.

> Also, after interpolating the data, function exporting the data back to .csv would be helpful.

What do you have in mind? Is plain `CSV.write` sufficient or you want a more fancy function, which, for example, adds units to column titles and writes the first line with a comment.

> * sometimes, one is interested in some specific time-series, then pipeline like: load data -> pick time-series (-> interpolate or process, if needed) -> write back to some csv - might be automated.

I'm not sure whether it is worth the effort. I've [documented how to filter a time range](https://ctu-iig.github.io/thermobench/dev/#Other-useful-data-manipulations). To interpolate that, you can extend the command with `... |> interpolate`. I can probably implement a `CSV.write` method that works directly with `Thermobench::Data`, so that you can write
```julia
@linq d.df |> where(10.0 .< :time .< 13.0) |> interpolate |> CSV.write("file.csv")
```
 
> * `multi_fit` function is useful when analyzing the T_inf and OPS of various benchmarks; for accessing the estimated steady state temperatures for further processing, I am currently using `CSV.write("table.csv", select(mf.result, Not([:fit,:data,:series])))`; function doing that automatically would be nice.

OK. Adding a method that allows you doing that with `CSV.write("table.csv", mf)` will be straightforward.

> * `multi_fit` plus functions like `plot_Tinf_and_ops` make nice comparisons across various benchmarks, but seemingly only for T_inf and OPS; now we might be able to measure even the Power (and possibly other things) - would it be possible to load multiple results, and plot bar charts similar to `T_inf_and_ops` which would be showing, e.g., average of a selected column (e.g., power)?

`plot_Tinf_and_ops` is just a simple wrapper over `Thermobench::plot_bars`. It should not be difficult.

> * add `title` argument to plot function

Already done in e2af12e.

> Most of these functions might already exist, but for non-Julia-expert it is not straightforward to use them. Maybe just adding some additional examples into the documentation might help.

**Comment by benedond** [comment]
Thank you for implementing the new features and updating the documentation. I think it is fine now, and this issue can be closed. If I think about some additional useful features, I will open a new issue.
